artifact_root: artifacts

data_ingestion:
  rootdir: artifacts/data_ingestion
  url: https://github.com/entbappy/Branching-tutorial/raw/master/winequality-data.zip
  localdir: artifacts/data_ingestion/data.zip
  unzipdir: artifacts/data_ingestion

data_validation:
  rootdir: artifacts/data_validation
  unzipdir: artifacts/data_ingestion/winequality-red.csv
  status: artifacts/data_validation/status.txt

data_transformation:
  rootdir: artifacts/data_transformation
  data: artifacts/data_ingestion/winequality-red.csv

model_trainer:
  rootdir: artifacts/model_trainer
  traindir: artifacts/data_transformation/train.csv
  testdir: artifacts/data_transformation/test.csv
  model: model.joblib

model_evaluation:
  rootdir: artifacts/model_evaluation
  testdir: artifacts/data_transformation/test.csv
  model: artifacts/model_trainer/model.joblib
  metrics_name: artifacts/model_evaluation/metrics.json